package msdmap.mapread;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Builds minimal, valid 4x4x4 float32 MRC fixtures on the fly for tests, so synthetic
 * edge-case maps don't need to be committed as binary files or generated by an external
 * Python script.
 */
public final class TestFixtures {

  private TestFixtures() {}

  public static void writeFixture(File path, String... labels) throws Exception {
    MapHeader header = new MapHeader();

    header.setWord(10, new int[]{1, 2, 3, 8, 9, 10, 4, 23, 17, 18},
        new String[]{"4", "4", "4", "4", "4", "4", "2", "1", "1", "2"});
    header.setWord(1, new int[]{19}, new String[]{"3"});
    header.setWord(3, new int[]{11, 12, 13}, new String[]{"4.0", "4.0", "4.0"});
    header.setWord(3, new int[]{14, 15, 16}, new String[]{"90.0", "90.0", "90.0"});
    header.setWord(1, new int[]{53}, new String[]{"MAP "});

    header.label = new String[10];
    for (int i = 0; i < labels.length; i++) header.label[i] = padTo80(labels[i]);
    header.setWord(1, new int[]{56}, new String[]{String.valueOf(labels.length)});

    byte[] data = new byte[4 * 4 * 4 * 4];
    ByteBuffer buffer = ByteBuffer.wrap(data).order(ByteOrder.LITTLE_ENDIAN);
    for (int i = 0; i < 64; i++) buffer.putFloat(i * 4, (float) i);

    File parent = path.getParentFile();
    if (parent != null) parent.mkdirs();

    MapWrite writer = new MapWrite();
    writer.setEndian(1);
    FileOutputStream out = writer.open(path.getPath());
    writer.write(out, header, data);
    writer.close(out);
  }

  // MapWrite always writes each label as a fixed 80-byte field, so every entry must be
  // padded/truncated to exactly 80 chars, matching MapHeader's own formatLabel contract.
  private static String padTo80(String text) {
    if (text == null) text = "";
    if (text.length() > 80) return text.substring(0, 80);
    StringBuilder sb = new StringBuilder(text);
    while (sb.length() < 80) sb.append(' ');
    return sb.toString();
  }
}
